/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/custom-endpoint/custom_endpoint_monitor.go

// Package mock_custom_endpoint is a generated GoMock package.
package mock_custom_endpoint

import (
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure"
	gomock "github.com/golang/mock/gomock"
)

// MockCustomEndpointMonitor is a mock of CustomEndpointMonitor interface.
type MockCustomEndpointMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockCustomEndpointMonitorMockRecorder
}

// MockCustomEndpointMonitorMockRecorder is the mock recorder for MockCustomEndpointMonitor.
type MockCustomEndpointMonitorMockRecorder struct {
	mock *MockCustomEndpointMonitor
}

// NewMockCustomEndpointMonitor creates a new mock instance.
func NewMockCustomEndpointMonitor(ctrl *gomock.Controller) *MockCustomEndpointMonitor {
	mock := &MockCustomEndpointMonitor{ctrl: ctrl}
	mock.recorder = &MockCustomEndpointMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomEndpointMonitor) EXPECT() *MockCustomEndpointMonitorMockRecorder {
	return m.recorder
}

// CanDispose mocks base method.
func (m *MockCustomEndpointMonitor) CanDispose() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDispose")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanDispose indicates an expected call of CanDispose.
func (mr *MockCustomEndpointMonitorMockRecorder) CanDispose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDispose", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).CanDispose))
}

// Close mocks base method.
func (m *MockCustomEndpointMonitor) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCustomEndpointMonitorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).Close))
}

// GetLastActivityTimestampNanos mocks base method.
func (m *MockCustomEndpointMonitor) GetLastActivityTimestampNanos() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastActivityTimestampNanos")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetLastActivityTimestampNanos indicates an expected call of GetLastActivityTimestampNanos.
func (mr *MockCustomEndpointMonitorMockRecorder) GetLastActivityTimestampNanos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastActivityTimestampNanos", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).GetLastActivityTimestampNanos))
}

// GetState mocks base method.
func (m *MockCustomEndpointMonitor) GetState() driver_infrastructure.MonitorState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(driver_infrastructure.MonitorState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockCustomEndpointMonitorMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).GetState))
}

// HasCustomEndpointInfo mocks base method.
func (m *MockCustomEndpointMonitor) HasCustomEndpointInfo() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCustomEndpointInfo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCustomEndpointInfo indicates an expected call of HasCustomEndpointInfo.
func (mr *MockCustomEndpointMonitorMockRecorder) HasCustomEndpointInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCustomEndpointInfo", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).HasCustomEndpointInfo))
}

// Monitor mocks base method.
func (m *MockCustomEndpointMonitor) Monitor() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Monitor")
}

// Monitor indicates an expected call of Monitor.
func (mr *MockCustomEndpointMonitorMockRecorder) Monitor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Monitor", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).Monitor))
}

// RequestCustomEndpointInfoUpdate mocks base method.
func (m *MockCustomEndpointMonitor) RequestCustomEndpointInfoUpdate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestCustomEndpointInfoUpdate")
}

// RequestCustomEndpointInfoUpdate indicates an expected call of RequestCustomEndpointInfoUpdate.
func (mr *MockCustomEndpointMonitorMockRecorder) RequestCustomEndpointInfoUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestCustomEndpointInfoUpdate", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).RequestCustomEndpointInfoUpdate))
}

// Start mocks base method.
func (m *MockCustomEndpointMonitor) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockCustomEndpointMonitorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).Start))
}

// Stop mocks base method.
func (m *MockCustomEndpointMonitor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCustomEndpointMonitorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).Stop))
}
