/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: custom-endpoint/custom_endpoint_monitor.go
//
// Generated by this command:
//
//	mockgen -source=custom-endpoint/custom_endpoint_monitor.go -destination=.test/test/mocks/custom-endpoint/mock_custom_endpoint_monitor.go package=mock_custom_endpoint
//

// Package mock_custom_endpoint is a generated GoMock package.
package mock_custom_endpoint

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomEndpointMonitor is a mock of CustomEndpointMonitor interface.
type MockCustomEndpointMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockCustomEndpointMonitorMockRecorder
	isgomock struct{}
}

// MockCustomEndpointMonitorMockRecorder is the mock recorder for MockCustomEndpointMonitor.
type MockCustomEndpointMonitorMockRecorder struct {
	mock *MockCustomEndpointMonitor
}

// NewMockCustomEndpointMonitor creates a new mock instance.
func NewMockCustomEndpointMonitor(ctrl *gomock.Controller) *MockCustomEndpointMonitor {
	mock := &MockCustomEndpointMonitor{ctrl: ctrl}
	mock.recorder = &MockCustomEndpointMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomEndpointMonitor) EXPECT() *MockCustomEndpointMonitorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCustomEndpointMonitor) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCustomEndpointMonitorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).Close))
}

// HasCustomEndpointInfo mocks base method.
func (m *MockCustomEndpointMonitor) HasCustomEndpointInfo() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCustomEndpointInfo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCustomEndpointInfo indicates an expected call of HasCustomEndpointInfo.
func (mr *MockCustomEndpointMonitorMockRecorder) HasCustomEndpointInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCustomEndpointInfo", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).HasCustomEndpointInfo))
}

// ShouldDispose mocks base method.
func (m *MockCustomEndpointMonitor) ShouldDispose() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldDispose")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldDispose indicates an expected call of ShouldDispose.
func (mr *MockCustomEndpointMonitorMockRecorder) ShouldDispose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldDispose", reflect.TypeOf((*MockCustomEndpointMonitor)(nil).ShouldDispose))
}
