version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/.test"
      - "/auth-helpers"
      - "/aws-secrets-manager"
      - "/awssql"
      - "/bun-pg-driver"
      - "/custom-endpoint"
      - "/federated-auth"
      - "/iam"
      - "/mysql-driver"
      - "/okta"
      - "/otlp"
      - "/pgx-driver"
      - "/xray"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
