/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure (interfaces: TopologyUtils,ClusterTopologyUtils,GlobalClusterTopologyUtils)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	driver "database/sql/driver"
	reflect "reflect"
	time "time"

	host_info_util "github.com/aws/aws-advanced-go-wrapper/awssql/host_info_util"
	gomock "github.com/golang/mock/gomock"
)

// MockTopologyUtils is a mock of TopologyUtils interface.
type MockTopologyUtils struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyUtilsMockRecorder
}

// MockTopologyUtilsMockRecorder is the mock recorder for MockTopologyUtils.
type MockTopologyUtilsMockRecorder struct {
	mock *MockTopologyUtils
}

// NewMockTopologyUtils creates a new mock instance.
func NewMockTopologyUtils(ctrl *gomock.Controller) *MockTopologyUtils {
	mock := &MockTopologyUtils{ctrl: ctrl}
	mock.recorder = &MockTopologyUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyUtils) EXPECT() *MockTopologyUtilsMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockTopologyUtils) CreateHost(arg0, arg1 string, arg2 bool, arg3 int, arg4 time.Time, arg5, arg6 *host_info_util.HostInfo) *host_info_util.HostInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*host_info_util.HostInfo)
	return ret0
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockTopologyUtilsMockRecorder) CreateHost(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockTopologyUtils)(nil).CreateHost), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// GetHostRole mocks base method.
func (m *MockTopologyUtils) GetHostRole(arg0 driver.Conn) host_info_util.HostRole {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostRole", arg0)
	ret0, _ := ret[0].(host_info_util.HostRole)
	return ret0
}

// GetHostRole indicates an expected call of GetHostRole.
func (mr *MockTopologyUtilsMockRecorder) GetHostRole(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostRole", reflect.TypeOf((*MockTopologyUtils)(nil).GetHostRole), arg0)
}

// GetInstanceId mocks base method.
func (m *MockTopologyUtils) GetInstanceId(arg0 driver.Conn) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceId", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetInstanceId indicates an expected call of GetInstanceId.
func (mr *MockTopologyUtilsMockRecorder) GetInstanceId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceId", reflect.TypeOf((*MockTopologyUtils)(nil).GetInstanceId), arg0)
}

// IsWriterInstance mocks base method.
func (m *MockTopologyUtils) IsWriterInstance(arg0 driver.Conn) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWriterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsWriterInstance indicates an expected call of IsWriterInstance.
func (mr *MockTopologyUtilsMockRecorder) IsWriterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWriterInstance", reflect.TypeOf((*MockTopologyUtils)(nil).IsWriterInstance), arg0)
}

// MockClusterTopologyUtils is a mock of ClusterTopologyUtils interface.
type MockClusterTopologyUtils struct {
	ctrl     *gomock.Controller
	recorder *MockClusterTopologyUtilsMockRecorder
}

// MockClusterTopologyUtilsMockRecorder is the mock recorder for MockClusterTopologyUtils.
type MockClusterTopologyUtilsMockRecorder struct {
	mock *MockClusterTopologyUtils
}

// NewMockClusterTopologyUtils creates a new mock instance.
func NewMockClusterTopologyUtils(ctrl *gomock.Controller) *MockClusterTopologyUtils {
	mock := &MockClusterTopologyUtils{ctrl: ctrl}
	mock.recorder = &MockClusterTopologyUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterTopologyUtils) EXPECT() *MockClusterTopologyUtilsMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockClusterTopologyUtils) CreateHost(arg0, arg1 string, arg2 bool, arg3 int, arg4 time.Time, arg5, arg6 *host_info_util.HostInfo) *host_info_util.HostInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*host_info_util.HostInfo)
	return ret0
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockClusterTopologyUtilsMockRecorder) CreateHost(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockClusterTopologyUtils)(nil).CreateHost), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// GetHostRole mocks base method.
func (m *MockClusterTopologyUtils) GetHostRole(arg0 driver.Conn) host_info_util.HostRole {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostRole", arg0)
	ret0, _ := ret[0].(host_info_util.HostRole)
	return ret0
}

// GetHostRole indicates an expected call of GetHostRole.
func (mr *MockClusterTopologyUtilsMockRecorder) GetHostRole(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostRole", reflect.TypeOf((*MockClusterTopologyUtils)(nil).GetHostRole), arg0)
}

// GetInstanceId mocks base method.
func (m *MockClusterTopologyUtils) GetInstanceId(arg0 driver.Conn) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceId", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetInstanceId indicates an expected call of GetInstanceId.
func (mr *MockClusterTopologyUtilsMockRecorder) GetInstanceId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceId", reflect.TypeOf((*MockClusterTopologyUtils)(nil).GetInstanceId), arg0)
}

// IsWriterInstance mocks base method.
func (m *MockClusterTopologyUtils) IsWriterInstance(arg0 driver.Conn) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWriterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsWriterInstance indicates an expected call of IsWriterInstance.
func (mr *MockClusterTopologyUtilsMockRecorder) IsWriterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWriterInstance", reflect.TypeOf((*MockClusterTopologyUtils)(nil).IsWriterInstance), arg0)
}

// QueryForTopology mocks base method.
func (m *MockClusterTopologyUtils) QueryForTopology(arg0 driver.Conn, arg1, arg2 *host_info_util.HostInfo) ([]*host_info_util.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryForTopology", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*host_info_util.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryForTopology indicates an expected call of QueryForTopology.
func (mr *MockClusterTopologyUtilsMockRecorder) QueryForTopology(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryForTopology", reflect.TypeOf((*MockClusterTopologyUtils)(nil).QueryForTopology), arg0, arg1, arg2)
}

// MockGlobalClusterTopologyUtils is a mock of GlobalClusterTopologyUtils interface.
type MockGlobalClusterTopologyUtils struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalClusterTopologyUtilsMockRecorder
}

// MockGlobalClusterTopologyUtilsMockRecorder is the mock recorder for MockGlobalClusterTopologyUtils.
type MockGlobalClusterTopologyUtilsMockRecorder struct {
	mock *MockGlobalClusterTopologyUtils
}

// NewMockGlobalClusterTopologyUtils creates a new mock instance.
func NewMockGlobalClusterTopologyUtils(ctrl *gomock.Controller) *MockGlobalClusterTopologyUtils {
	mock := &MockGlobalClusterTopologyUtils{ctrl: ctrl}
	mock.recorder = &MockGlobalClusterTopologyUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalClusterTopologyUtils) EXPECT() *MockGlobalClusterTopologyUtilsMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockGlobalClusterTopologyUtils) CreateHost(arg0, arg1 string, arg2 bool, arg3 int, arg4 time.Time, arg5, arg6 *host_info_util.HostInfo) *host_info_util.HostInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*host_info_util.HostInfo)
	return ret0
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) CreateHost(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).CreateHost), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// GetHostRole mocks base method.
func (m *MockGlobalClusterTopologyUtils) GetHostRole(arg0 driver.Conn) host_info_util.HostRole {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostRole", arg0)
	ret0, _ := ret[0].(host_info_util.HostRole)
	return ret0
}

// GetHostRole indicates an expected call of GetHostRole.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) GetHostRole(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostRole", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).GetHostRole), arg0)
}

// GetInstanceId mocks base method.
func (m *MockGlobalClusterTopologyUtils) GetInstanceId(arg0 driver.Conn) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceId", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetInstanceId indicates an expected call of GetInstanceId.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) GetInstanceId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceId", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).GetInstanceId), arg0)
}

// GetRegion mocks base method.
func (m *MockGlobalClusterTopologyUtils) GetRegion(arg0 string, arg1 driver.Conn) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) GetRegion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).GetRegion), arg0, arg1)
}

// IsWriterInstance mocks base method.
func (m *MockGlobalClusterTopologyUtils) IsWriterInstance(arg0 driver.Conn) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWriterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsWriterInstance indicates an expected call of IsWriterInstance.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) IsWriterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWriterInstance", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).IsWriterInstance), arg0)
}

// QueryForTopologyByRegion mocks base method.
func (m *MockGlobalClusterTopologyUtils) QueryForTopologyByRegion(arg0 driver.Conn, arg1 *host_info_util.HostInfo, arg2 map[string]*host_info_util.HostInfo) ([]*host_info_util.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryForTopologyByRegion", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*host_info_util.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryForTopologyByRegion indicates an expected call of QueryForTopologyByRegion.
func (mr *MockGlobalClusterTopologyUtilsMockRecorder) QueryForTopologyByRegion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryForTopologyByRegion", reflect.TypeOf((*MockGlobalClusterTopologyUtils)(nil).QueryForTopologyByRegion), arg0, arg1, arg2)
}
