/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure (interfaces: MonitorService)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure"
	gomock "github.com/golang/mock/gomock"
)

// MockMonitorService is a mock of MonitorService interface.
type MockMonitorService struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorServiceMockRecorder
}

// MockMonitorServiceMockRecorder is the mock recorder for MockMonitorService.
type MockMonitorServiceMockRecorder struct {
	mock *MockMonitorService
}

// NewMockMonitorService creates a new mock instance.
func NewMockMonitorService(ctrl *gomock.Controller) *MockMonitorService {
	mock := &MockMonitorService{ctrl: ctrl}
	mock.recorder = &MockMonitorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorService) EXPECT() *MockMonitorServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMonitorService) Get(arg0 *driver_infrastructure.MonitorType, arg1 interface{}) driver_infrastructure.Monitor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(driver_infrastructure.Monitor)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockMonitorServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMonitorService)(nil).Get), arg0, arg1)
}

// RegisterMonitorType mocks base method.
func (m *MockMonitorService) RegisterMonitorType(arg0 *driver_infrastructure.MonitorType, arg1 *driver_infrastructure.MonitorSettings, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterMonitorType", arg0, arg1, arg2)
}

// RegisterMonitorType indicates an expected call of RegisterMonitorType.
func (mr *MockMonitorServiceMockRecorder) RegisterMonitorType(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMonitorType", reflect.TypeOf((*MockMonitorService)(nil).RegisterMonitorType), arg0, arg1, arg2)
}

// ReleaseResources mocks base method.
func (m *MockMonitorService) ReleaseResources() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseResources")
}

// ReleaseResources indicates an expected call of ReleaseResources.
func (mr *MockMonitorServiceMockRecorder) ReleaseResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseResources", reflect.TypeOf((*MockMonitorService)(nil).ReleaseResources))
}

// Remove mocks base method.
func (m *MockMonitorService) Remove(arg0 *driver_infrastructure.MonitorType, arg1 interface{}) driver_infrastructure.Monitor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(driver_infrastructure.Monitor)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMonitorServiceMockRecorder) Remove(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMonitorService)(nil).Remove), arg0, arg1)
}

// RunIfAbsent mocks base method.
func (m *MockMonitorService) RunIfAbsent(arg0 *driver_infrastructure.MonitorType, arg1 interface{}, arg2 driver_infrastructure.ServicesContainer, arg3 driver_infrastructure.MonitorInitializer) (driver_infrastructure.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunIfAbsent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(driver_infrastructure.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunIfAbsent indicates an expected call of RunIfAbsent.
func (mr *MockMonitorServiceMockRecorder) RunIfAbsent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunIfAbsent", reflect.TypeOf((*MockMonitorService)(nil).RunIfAbsent), arg0, arg1, arg2, arg3)
}

// StopAndRemove mocks base method.
func (m *MockMonitorService) StopAndRemove(arg0 *driver_infrastructure.MonitorType, arg1 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAndRemove", arg0, arg1)
}

// StopAndRemove indicates an expected call of StopAndRemove.
func (mr *MockMonitorServiceMockRecorder) StopAndRemove(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAndRemove", reflect.TypeOf((*MockMonitorService)(nil).StopAndRemove), arg0, arg1)
}

// StopAndRemoveAll mocks base method.
func (m *MockMonitorService) StopAndRemoveAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAndRemoveAll")
}

// StopAndRemoveAll indicates an expected call of StopAndRemoveAll.
func (mr *MockMonitorServiceMockRecorder) StopAndRemoveAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAndRemoveAll", reflect.TypeOf((*MockMonitorService)(nil).StopAndRemoveAll))
}

// StopAndRemoveByType mocks base method.
func (m *MockMonitorService) StopAndRemoveByType(arg0 *driver_infrastructure.MonitorType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAndRemoveByType", arg0)
}

// StopAndRemoveByType indicates an expected call of StopAndRemoveByType.
func (mr *MockMonitorServiceMockRecorder) StopAndRemoveByType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAndRemoveByType", reflect.TypeOf((*MockMonitorService)(nil).StopAndRemoveByType), arg0)
}
