// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure (interfaces: ClusterTopologyMonitor)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure"
	host_info_util "github.com/aws/aws-advanced-go-wrapper/awssql/host_info_util"
	gomock "github.com/golang/mock/gomock"
)

// MockClusterTopologyMonitor is a mock of ClusterTopologyMonitor interface.
type MockClusterTopologyMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockClusterTopologyMonitorMockRecorder
}

// MockClusterTopologyMonitorMockRecorder is the mock recorder for MockClusterTopologyMonitor.
type MockClusterTopologyMonitorMockRecorder struct {
	mock *MockClusterTopologyMonitor
}

// NewMockClusterTopologyMonitor creates a new mock instance.
func NewMockClusterTopologyMonitor(ctrl *gomock.Controller) *MockClusterTopologyMonitor {
	mock := &MockClusterTopologyMonitor{ctrl: ctrl}
	mock.recorder = &MockClusterTopologyMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterTopologyMonitor) EXPECT() *MockClusterTopologyMonitorMockRecorder {
	return m.recorder
}

// CanDispose mocks base method.
func (m *MockClusterTopologyMonitor) CanDispose() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDispose")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanDispose indicates an expected call of CanDispose.
func (mr *MockClusterTopologyMonitorMockRecorder) CanDispose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDispose", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).CanDispose))
}

// Close mocks base method.
func (m *MockClusterTopologyMonitor) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClusterTopologyMonitorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).Close))
}

// ForceRefresh mocks base method.
func (m *MockClusterTopologyMonitor) ForceRefresh(arg0 bool, arg1 int) ([]*host_info_util.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceRefresh", arg0, arg1)
	ret0, _ := ret[0].([]*host_info_util.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceRefresh indicates an expected call of ForceRefresh.
func (mr *MockClusterTopologyMonitorMockRecorder) ForceRefresh(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceRefresh", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).ForceRefresh), arg0, arg1)
}

// GetLastActivityTimestampNanos mocks base method.
func (m *MockClusterTopologyMonitor) GetLastActivityTimestampNanos() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastActivityTimestampNanos")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetLastActivityTimestampNanos indicates an expected call of GetLastActivityTimestampNanos.
func (mr *MockClusterTopologyMonitorMockRecorder) GetLastActivityTimestampNanos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastActivityTimestampNanos", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).GetLastActivityTimestampNanos))
}

// GetState mocks base method.
func (m *MockClusterTopologyMonitor) GetState() driver_infrastructure.MonitorState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(driver_infrastructure.MonitorState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockClusterTopologyMonitorMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).GetState))
}

// Monitor mocks base method.
func (m *MockClusterTopologyMonitor) Monitor() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Monitor")
}

// Monitor indicates an expected call of Monitor.
func (mr *MockClusterTopologyMonitorMockRecorder) Monitor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Monitor", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).Monitor))
}

// ProcessEvent mocks base method.
func (m *MockClusterTopologyMonitor) ProcessEvent(arg0 driver_infrastructure.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessEvent", arg0)
}

// ProcessEvent indicates an expected call of ProcessEvent.
func (mr *MockClusterTopologyMonitorMockRecorder) ProcessEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).ProcessEvent), arg0)
}

// Start mocks base method.
func (m *MockClusterTopologyMonitor) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockClusterTopologyMonitorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).Start))
}

// Stop mocks base method.
func (m *MockClusterTopologyMonitor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockClusterTopologyMonitorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockClusterTopologyMonitor)(nil).Stop))
}
