/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: ../awssql/driver_infrastructure/topology_utils.go

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	driver "database/sql/driver"
	reflect "reflect"
	time "time"

	host_info_util "github.com/aws/aws-advanced-go-wrapper/awssql/host_info_util"
	gomock "github.com/golang/mock/gomock"
)

// MockTopologyUtils is a mock of TopologyUtils interface.
type MockTopologyUtils struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyUtilsMockRecorder
}

// MockTopologyUtilsMockRecorder is the mock recorder for MockTopologyUtils.
type MockTopologyUtilsMockRecorder struct {
	mock *MockTopologyUtils
}

// NewMockTopologyUtils creates a new mock instance.
func NewMockTopologyUtils(ctrl *gomock.Controller) *MockTopologyUtils {
	mock := &MockTopologyUtils{ctrl: ctrl}
	mock.recorder = &MockTopologyUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyUtils) EXPECT() *MockTopologyUtilsMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockTopologyUtils) CreateHost(instanceId, instanceName string, isWriter bool, weight int, lastUpdateTime time.Time, initialHost, instanceTemplate *host_info_util.HostInfo) *host_info_util.HostInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", instanceId, instanceName, isWriter, weight, lastUpdateTime, initialHost, instanceTemplate)
	ret0, _ := ret[0].(*host_info_util.HostInfo)
	return ret0
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockTopologyUtilsMockRecorder) CreateHost(instanceId, instanceName, isWriter, weight, lastUpdateTime, initialHost, instanceTemplate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockTopologyUtils)(nil).CreateHost), instanceId, instanceName, isWriter, weight, lastUpdateTime, initialHost, instanceTemplate)
}

// GetHostRole mocks base method.
func (m *MockTopologyUtils) GetHostRole(conn driver.Conn) host_info_util.HostRole {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostRole", conn)
	ret0, _ := ret[0].(host_info_util.HostRole)
	return ret0
}

// GetHostRole indicates an expected call of GetHostRole.
func (mr *MockTopologyUtilsMockRecorder) GetHostRole(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostRole", reflect.TypeOf((*MockTopologyUtils)(nil).GetHostRole), conn)
}

// GetInstanceId mocks base method.
func (m *MockTopologyUtils) GetInstanceId(conn driver.Conn) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceId", conn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetInstanceId indicates an expected call of GetInstanceId.
func (mr *MockTopologyUtilsMockRecorder) GetInstanceId(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceId", reflect.TypeOf((*MockTopologyUtils)(nil).GetInstanceId), conn)
}

// IsWriterInstance mocks base method.
func (m *MockTopologyUtils) IsWriterInstance(conn driver.Conn) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWriterInstance", conn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsWriterInstance indicates an expected call of IsWriterInstance.
func (mr *MockTopologyUtilsMockRecorder) IsWriterInstance(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWriterInstance", reflect.TypeOf((*MockTopologyUtils)(nil).IsWriterInstance), conn)
}

// QueryForTopology mocks base method.
func (m *MockTopologyUtils) QueryForTopology(conn driver.Conn, initialHost, instanceTemplate *host_info_util.HostInfo) ([]*host_info_util.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryForTopology", conn, initialHost, instanceTemplate)
	ret0, _ := ret[0].([]*host_info_util.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryForTopology indicates an expected call of QueryForTopology.
func (mr *MockTopologyUtilsMockRecorder) QueryForTopology(conn, initialHost, instanceTemplate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryForTopology", reflect.TypeOf((*MockTopologyUtils)(nil).QueryForTopology), conn, initialHost, instanceTemplate)
}
