/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure (interfaces: DatabaseDialect,TopologyDialect,AuroraLimitlessDialect,BlueGreenDialect)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	driver "database/sql/driver"
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure"
	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseDialect is a mock of DatabaseDialect interface.
type MockDatabaseDialect struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseDialectMockRecorder
}

// MockDatabaseDialectMockRecorder is the mock recorder for MockDatabaseDialect.
type MockDatabaseDialectMockRecorder struct {
	mock *MockDatabaseDialect
}

// NewMockDatabaseDialect creates a new mock instance.
func NewMockDatabaseDialect(ctrl *gomock.Controller) *MockDatabaseDialect {
	mock := &MockDatabaseDialect{ctrl: ctrl}
	mock.recorder = &MockDatabaseDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseDialect) EXPECT() *MockDatabaseDialectMockRecorder {
	return m.recorder
}

// DoesStatementSetAutoCommit mocks base method.
func (m *MockDatabaseDialect) DoesStatementSetAutoCommit(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetAutoCommit", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetAutoCommit indicates an expected call of DoesStatementSetAutoCommit.
func (mr *MockDatabaseDialectMockRecorder) DoesStatementSetAutoCommit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetAutoCommit", reflect.TypeOf((*MockDatabaseDialect)(nil).DoesStatementSetAutoCommit), arg0)
}

// DoesStatementSetCatalog mocks base method.
func (m *MockDatabaseDialect) DoesStatementSetCatalog(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetCatalog", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetCatalog indicates an expected call of DoesStatementSetCatalog.
func (mr *MockDatabaseDialectMockRecorder) DoesStatementSetCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetCatalog", reflect.TypeOf((*MockDatabaseDialect)(nil).DoesStatementSetCatalog), arg0)
}

// DoesStatementSetReadOnly mocks base method.
func (m *MockDatabaseDialect) DoesStatementSetReadOnly(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetReadOnly", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetReadOnly indicates an expected call of DoesStatementSetReadOnly.
func (mr *MockDatabaseDialectMockRecorder) DoesStatementSetReadOnly(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetReadOnly", reflect.TypeOf((*MockDatabaseDialect)(nil).DoesStatementSetReadOnly), arg0)
}

// DoesStatementSetSchema mocks base method.
func (m *MockDatabaseDialect) DoesStatementSetSchema(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetSchema", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetSchema indicates an expected call of DoesStatementSetSchema.
func (mr *MockDatabaseDialectMockRecorder) DoesStatementSetSchema(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetSchema", reflect.TypeOf((*MockDatabaseDialect)(nil).DoesStatementSetSchema), arg0)
}

// DoesStatementSetTransactionIsolation mocks base method.
func (m *MockDatabaseDialect) DoesStatementSetTransactionIsolation(arg0 string) (driver_infrastructure.TransactionIsolationLevel, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetTransactionIsolation", arg0)
	ret0, _ := ret[0].(driver_infrastructure.TransactionIsolationLevel)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetTransactionIsolation indicates an expected call of DoesStatementSetTransactionIsolation.
func (mr *MockDatabaseDialectMockRecorder) DoesStatementSetTransactionIsolation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetTransactionIsolation", reflect.TypeOf((*MockDatabaseDialect)(nil).DoesStatementSetTransactionIsolation), arg0)
}

// GetDefaultPort mocks base method.
func (m *MockDatabaseDialect) GetDefaultPort() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPort")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDefaultPort indicates an expected call of GetDefaultPort.
func (mr *MockDatabaseDialectMockRecorder) GetDefaultPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPort", reflect.TypeOf((*MockDatabaseDialect)(nil).GetDefaultPort))
}

// GetDialectUpdateCandidates mocks base method.
func (m *MockDatabaseDialect) GetDialectUpdateCandidates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialectUpdateCandidates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDialectUpdateCandidates indicates an expected call of GetDialectUpdateCandidates.
func (mr *MockDatabaseDialectMockRecorder) GetDialectUpdateCandidates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialectUpdateCandidates", reflect.TypeOf((*MockDatabaseDialect)(nil).GetDialectUpdateCandidates))
}

// GetHostAliasQuery mocks base method.
func (m *MockDatabaseDialect) GetHostAliasQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostAliasQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHostAliasQuery indicates an expected call of GetHostAliasQuery.
func (mr *MockDatabaseDialectMockRecorder) GetHostAliasQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostAliasQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetHostAliasQuery))
}

// GetHostListProviderSupplier mocks base method.
func (m *MockDatabaseDialect) GetHostListProviderSupplier() driver_infrastructure.HostListProviderSupplier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostListProviderSupplier")
	ret0, _ := ret[0].(driver_infrastructure.HostListProviderSupplier)
	return ret0
}

// GetHostListProviderSupplier indicates an expected call of GetHostListProviderSupplier.
func (mr *MockDatabaseDialectMockRecorder) GetHostListProviderSupplier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostListProviderSupplier", reflect.TypeOf((*MockDatabaseDialect)(nil).GetHostListProviderSupplier))
}

// GetIsReaderQuery mocks base method.
func (m *MockDatabaseDialect) GetIsReaderQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsReaderQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIsReaderQuery indicates an expected call of GetIsReaderQuery.
func (mr *MockDatabaseDialectMockRecorder) GetIsReaderQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsReaderQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetIsReaderQuery))
}

// GetRowParser mocks base method.
func (m *MockDatabaseDialect) GetRowParser() driver_infrastructure.RowParser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowParser")
	ret0, _ := ret[0].(driver_infrastructure.RowParser)
	return ret0
}

// GetRowParser indicates an expected call of GetRowParser.
func (mr *MockDatabaseDialectMockRecorder) GetRowParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowParser", reflect.TypeOf((*MockDatabaseDialect)(nil).GetRowParser))
}

// GetServerVersionQuery mocks base method.
func (m *MockDatabaseDialect) GetServerVersionQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerVersionQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerVersionQuery indicates an expected call of GetServerVersionQuery.
func (mr *MockDatabaseDialectMockRecorder) GetServerVersionQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerVersionQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetServerVersionQuery))
}

// GetSetAutoCommitQuery mocks base method.
func (m *MockDatabaseDialect) GetSetAutoCommitQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetAutoCommitQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetAutoCommitQuery indicates an expected call of GetSetAutoCommitQuery.
func (mr *MockDatabaseDialectMockRecorder) GetSetAutoCommitQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetAutoCommitQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetSetAutoCommitQuery), arg0)
}

// GetSetCatalogQuery mocks base method.
func (m *MockDatabaseDialect) GetSetCatalogQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetCatalogQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetCatalogQuery indicates an expected call of GetSetCatalogQuery.
func (mr *MockDatabaseDialectMockRecorder) GetSetCatalogQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetCatalogQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetSetCatalogQuery), arg0)
}

// GetSetReadOnlyQuery mocks base method.
func (m *MockDatabaseDialect) GetSetReadOnlyQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetReadOnlyQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetReadOnlyQuery indicates an expected call of GetSetReadOnlyQuery.
func (mr *MockDatabaseDialectMockRecorder) GetSetReadOnlyQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetReadOnlyQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetSetReadOnlyQuery), arg0)
}

// GetSetSchemaQuery mocks base method.
func (m *MockDatabaseDialect) GetSetSchemaQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetSchemaQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetSchemaQuery indicates an expected call of GetSetSchemaQuery.
func (mr *MockDatabaseDialectMockRecorder) GetSetSchemaQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetSchemaQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetSetSchemaQuery), arg0)
}

// GetSetTransactionIsolationQuery mocks base method.
func (m *MockDatabaseDialect) GetSetTransactionIsolationQuery(arg0 driver_infrastructure.TransactionIsolationLevel) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetTransactionIsolationQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetTransactionIsolationQuery indicates an expected call of GetSetTransactionIsolationQuery.
func (mr *MockDatabaseDialectMockRecorder) GetSetTransactionIsolationQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetTransactionIsolationQuery", reflect.TypeOf((*MockDatabaseDialect)(nil).GetSetTransactionIsolationQuery), arg0)
}

// IsDialect mocks base method.
func (m *MockDatabaseDialect) IsDialect(arg0 driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialect", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDialect indicates an expected call of IsDialect.
func (mr *MockDatabaseDialectMockRecorder) IsDialect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialect", reflect.TypeOf((*MockDatabaseDialect)(nil).IsDialect), arg0)
}

// MockTopologyDialect is a mock of TopologyDialect interface.
type MockTopologyDialect struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyDialectMockRecorder
}

// MockTopologyDialectMockRecorder is the mock recorder for MockTopologyDialect.
type MockTopologyDialectMockRecorder struct {
	mock *MockTopologyDialect
}

// NewMockTopologyDialect creates a new mock instance.
func NewMockTopologyDialect(ctrl *gomock.Controller) *MockTopologyDialect {
	mock := &MockTopologyDialect{ctrl: ctrl}
	mock.recorder = &MockTopologyDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyDialect) EXPECT() *MockTopologyDialectMockRecorder {
	return m.recorder
}

// DoesStatementSetAutoCommit mocks base method.
func (m *MockTopologyDialect) DoesStatementSetAutoCommit(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetAutoCommit", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetAutoCommit indicates an expected call of DoesStatementSetAutoCommit.
func (mr *MockTopologyDialectMockRecorder) DoesStatementSetAutoCommit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetAutoCommit", reflect.TypeOf((*MockTopologyDialect)(nil).DoesStatementSetAutoCommit), arg0)
}

// DoesStatementSetCatalog mocks base method.
func (m *MockTopologyDialect) DoesStatementSetCatalog(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetCatalog", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetCatalog indicates an expected call of DoesStatementSetCatalog.
func (mr *MockTopologyDialectMockRecorder) DoesStatementSetCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetCatalog", reflect.TypeOf((*MockTopologyDialect)(nil).DoesStatementSetCatalog), arg0)
}

// DoesStatementSetReadOnly mocks base method.
func (m *MockTopologyDialect) DoesStatementSetReadOnly(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetReadOnly", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetReadOnly indicates an expected call of DoesStatementSetReadOnly.
func (mr *MockTopologyDialectMockRecorder) DoesStatementSetReadOnly(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetReadOnly", reflect.TypeOf((*MockTopologyDialect)(nil).DoesStatementSetReadOnly), arg0)
}

// DoesStatementSetSchema mocks base method.
func (m *MockTopologyDialect) DoesStatementSetSchema(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetSchema", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetSchema indicates an expected call of DoesStatementSetSchema.
func (mr *MockTopologyDialectMockRecorder) DoesStatementSetSchema(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetSchema", reflect.TypeOf((*MockTopologyDialect)(nil).DoesStatementSetSchema), arg0)
}

// DoesStatementSetTransactionIsolation mocks base method.
func (m *MockTopologyDialect) DoesStatementSetTransactionIsolation(arg0 string) (driver_infrastructure.TransactionIsolationLevel, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetTransactionIsolation", arg0)
	ret0, _ := ret[0].(driver_infrastructure.TransactionIsolationLevel)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetTransactionIsolation indicates an expected call of DoesStatementSetTransactionIsolation.
func (mr *MockTopologyDialectMockRecorder) DoesStatementSetTransactionIsolation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetTransactionIsolation", reflect.TypeOf((*MockTopologyDialect)(nil).DoesStatementSetTransactionIsolation), arg0)
}

// GetDefaultPort mocks base method.
func (m *MockTopologyDialect) GetDefaultPort() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPort")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDefaultPort indicates an expected call of GetDefaultPort.
func (mr *MockTopologyDialectMockRecorder) GetDefaultPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPort", reflect.TypeOf((*MockTopologyDialect)(nil).GetDefaultPort))
}

// GetDialectUpdateCandidates mocks base method.
func (m *MockTopologyDialect) GetDialectUpdateCandidates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialectUpdateCandidates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDialectUpdateCandidates indicates an expected call of GetDialectUpdateCandidates.
func (mr *MockTopologyDialectMockRecorder) GetDialectUpdateCandidates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialectUpdateCandidates", reflect.TypeOf((*MockTopologyDialect)(nil).GetDialectUpdateCandidates))
}

// GetHostAliasQuery mocks base method.
func (m *MockTopologyDialect) GetHostAliasQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostAliasQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHostAliasQuery indicates an expected call of GetHostAliasQuery.
func (mr *MockTopologyDialectMockRecorder) GetHostAliasQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostAliasQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetHostAliasQuery))
}

// GetHostListProviderSupplier mocks base method.
func (m *MockTopologyDialect) GetHostListProviderSupplier() driver_infrastructure.HostListProviderSupplier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostListProviderSupplier")
	ret0, _ := ret[0].(driver_infrastructure.HostListProviderSupplier)
	return ret0
}

// GetHostListProviderSupplier indicates an expected call of GetHostListProviderSupplier.
func (mr *MockTopologyDialectMockRecorder) GetHostListProviderSupplier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostListProviderSupplier", reflect.TypeOf((*MockTopologyDialect)(nil).GetHostListProviderSupplier))
}

// GetInstanceIdQuery mocks base method.
func (m *MockTopologyDialect) GetInstanceIdQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceIdQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInstanceIdQuery indicates an expected call of GetInstanceIdQuery.
func (mr *MockTopologyDialectMockRecorder) GetInstanceIdQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceIdQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetInstanceIdQuery))
}

// GetIsReaderQuery mocks base method.
func (m *MockTopologyDialect) GetIsReaderQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsReaderQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIsReaderQuery indicates an expected call of GetIsReaderQuery.
func (mr *MockTopologyDialectMockRecorder) GetIsReaderQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsReaderQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetIsReaderQuery))
}

// GetRowParser mocks base method.
func (m *MockTopologyDialect) GetRowParser() driver_infrastructure.RowParser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowParser")
	ret0, _ := ret[0].(driver_infrastructure.RowParser)
	return ret0
}

// GetRowParser indicates an expected call of GetRowParser.
func (mr *MockTopologyDialectMockRecorder) GetRowParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowParser", reflect.TypeOf((*MockTopologyDialect)(nil).GetRowParser))
}

// GetServerVersionQuery mocks base method.
func (m *MockTopologyDialect) GetServerVersionQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerVersionQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerVersionQuery indicates an expected call of GetServerVersionQuery.
func (mr *MockTopologyDialectMockRecorder) GetServerVersionQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerVersionQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetServerVersionQuery))
}

// GetSetAutoCommitQuery mocks base method.
func (m *MockTopologyDialect) GetSetAutoCommitQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetAutoCommitQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetAutoCommitQuery indicates an expected call of GetSetAutoCommitQuery.
func (mr *MockTopologyDialectMockRecorder) GetSetAutoCommitQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetAutoCommitQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetSetAutoCommitQuery), arg0)
}

// GetSetCatalogQuery mocks base method.
func (m *MockTopologyDialect) GetSetCatalogQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetCatalogQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetCatalogQuery indicates an expected call of GetSetCatalogQuery.
func (mr *MockTopologyDialectMockRecorder) GetSetCatalogQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetCatalogQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetSetCatalogQuery), arg0)
}

// GetSetReadOnlyQuery mocks base method.
func (m *MockTopologyDialect) GetSetReadOnlyQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetReadOnlyQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetReadOnlyQuery indicates an expected call of GetSetReadOnlyQuery.
func (mr *MockTopologyDialectMockRecorder) GetSetReadOnlyQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetReadOnlyQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetSetReadOnlyQuery), arg0)
}

// GetSetSchemaQuery mocks base method.
func (m *MockTopologyDialect) GetSetSchemaQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetSchemaQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetSchemaQuery indicates an expected call of GetSetSchemaQuery.
func (mr *MockTopologyDialectMockRecorder) GetSetSchemaQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetSchemaQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetSetSchemaQuery), arg0)
}

// GetSetTransactionIsolationQuery mocks base method.
func (m *MockTopologyDialect) GetSetTransactionIsolationQuery(arg0 driver_infrastructure.TransactionIsolationLevel) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetTransactionIsolationQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetTransactionIsolationQuery indicates an expected call of GetSetTransactionIsolationQuery.
func (mr *MockTopologyDialectMockRecorder) GetSetTransactionIsolationQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetTransactionIsolationQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetSetTransactionIsolationQuery), arg0)
}

// GetTopologyQuery mocks base method.
func (m *MockTopologyDialect) GetTopologyQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopologyQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTopologyQuery indicates an expected call of GetTopologyQuery.
func (mr *MockTopologyDialectMockRecorder) GetTopologyQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopologyQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetTopologyQuery))
}

// GetWriterIdQuery mocks base method.
func (m *MockTopologyDialect) GetWriterIdQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWriterIdQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWriterIdQuery indicates an expected call of GetWriterIdQuery.
func (mr *MockTopologyDialectMockRecorder) GetWriterIdQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWriterIdQuery", reflect.TypeOf((*MockTopologyDialect)(nil).GetWriterIdQuery))
}

// IsDialect mocks base method.
func (m *MockTopologyDialect) IsDialect(arg0 driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialect", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDialect indicates an expected call of IsDialect.
func (mr *MockTopologyDialectMockRecorder) IsDialect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialect", reflect.TypeOf((*MockTopologyDialect)(nil).IsDialect), arg0)
}

// MockAuroraLimitlessDialect is a mock of AuroraLimitlessDialect interface.
type MockAuroraLimitlessDialect struct {
	ctrl     *gomock.Controller
	recorder *MockAuroraLimitlessDialectMockRecorder
}

// MockAuroraLimitlessDialectMockRecorder is the mock recorder for MockAuroraLimitlessDialect.
type MockAuroraLimitlessDialectMockRecorder struct {
	mock *MockAuroraLimitlessDialect
}

// NewMockAuroraLimitlessDialect creates a new mock instance.
func NewMockAuroraLimitlessDialect(ctrl *gomock.Controller) *MockAuroraLimitlessDialect {
	mock := &MockAuroraLimitlessDialect{ctrl: ctrl}
	mock.recorder = &MockAuroraLimitlessDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuroraLimitlessDialect) EXPECT() *MockAuroraLimitlessDialectMockRecorder {
	return m.recorder
}

// DoesStatementSetAutoCommit mocks base method.
func (m *MockAuroraLimitlessDialect) DoesStatementSetAutoCommit(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetAutoCommit", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetAutoCommit indicates an expected call of DoesStatementSetAutoCommit.
func (mr *MockAuroraLimitlessDialectMockRecorder) DoesStatementSetAutoCommit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetAutoCommit", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).DoesStatementSetAutoCommit), arg0)
}

// DoesStatementSetCatalog mocks base method.
func (m *MockAuroraLimitlessDialect) DoesStatementSetCatalog(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetCatalog", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetCatalog indicates an expected call of DoesStatementSetCatalog.
func (mr *MockAuroraLimitlessDialectMockRecorder) DoesStatementSetCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetCatalog", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).DoesStatementSetCatalog), arg0)
}

// DoesStatementSetReadOnly mocks base method.
func (m *MockAuroraLimitlessDialect) DoesStatementSetReadOnly(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetReadOnly", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetReadOnly indicates an expected call of DoesStatementSetReadOnly.
func (mr *MockAuroraLimitlessDialectMockRecorder) DoesStatementSetReadOnly(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetReadOnly", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).DoesStatementSetReadOnly), arg0)
}

// DoesStatementSetSchema mocks base method.
func (m *MockAuroraLimitlessDialect) DoesStatementSetSchema(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetSchema", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetSchema indicates an expected call of DoesStatementSetSchema.
func (mr *MockAuroraLimitlessDialectMockRecorder) DoesStatementSetSchema(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetSchema", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).DoesStatementSetSchema), arg0)
}

// DoesStatementSetTransactionIsolation mocks base method.
func (m *MockAuroraLimitlessDialect) DoesStatementSetTransactionIsolation(arg0 string) (driver_infrastructure.TransactionIsolationLevel, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetTransactionIsolation", arg0)
	ret0, _ := ret[0].(driver_infrastructure.TransactionIsolationLevel)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetTransactionIsolation indicates an expected call of DoesStatementSetTransactionIsolation.
func (mr *MockAuroraLimitlessDialectMockRecorder) DoesStatementSetTransactionIsolation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetTransactionIsolation", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).DoesStatementSetTransactionIsolation), arg0)
}

// GetDefaultPort mocks base method.
func (m *MockAuroraLimitlessDialect) GetDefaultPort() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPort")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDefaultPort indicates an expected call of GetDefaultPort.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetDefaultPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPort", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetDefaultPort))
}

// GetDialectUpdateCandidates mocks base method.
func (m *MockAuroraLimitlessDialect) GetDialectUpdateCandidates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialectUpdateCandidates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDialectUpdateCandidates indicates an expected call of GetDialectUpdateCandidates.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetDialectUpdateCandidates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialectUpdateCandidates", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetDialectUpdateCandidates))
}

// GetHostAliasQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetHostAliasQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostAliasQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHostAliasQuery indicates an expected call of GetHostAliasQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetHostAliasQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostAliasQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetHostAliasQuery))
}

// GetHostListProviderSupplier mocks base method.
func (m *MockAuroraLimitlessDialect) GetHostListProviderSupplier() driver_infrastructure.HostListProviderSupplier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostListProviderSupplier")
	ret0, _ := ret[0].(driver_infrastructure.HostListProviderSupplier)
	return ret0
}

// GetHostListProviderSupplier indicates an expected call of GetHostListProviderSupplier.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetHostListProviderSupplier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostListProviderSupplier", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetHostListProviderSupplier))
}

// GetIsReaderQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetIsReaderQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsReaderQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIsReaderQuery indicates an expected call of GetIsReaderQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetIsReaderQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsReaderQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetIsReaderQuery))
}

// GetLimitlessRouterEndpointQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetLimitlessRouterEndpointQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimitlessRouterEndpointQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLimitlessRouterEndpointQuery indicates an expected call of GetLimitlessRouterEndpointQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetLimitlessRouterEndpointQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimitlessRouterEndpointQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetLimitlessRouterEndpointQuery))
}

// GetRowParser mocks base method.
func (m *MockAuroraLimitlessDialect) GetRowParser() driver_infrastructure.RowParser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowParser")
	ret0, _ := ret[0].(driver_infrastructure.RowParser)
	return ret0
}

// GetRowParser indicates an expected call of GetRowParser.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetRowParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowParser", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetRowParser))
}

// GetServerVersionQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetServerVersionQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerVersionQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerVersionQuery indicates an expected call of GetServerVersionQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetServerVersionQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerVersionQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetServerVersionQuery))
}

// GetSetAutoCommitQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetSetAutoCommitQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetAutoCommitQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetAutoCommitQuery indicates an expected call of GetSetAutoCommitQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetSetAutoCommitQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetAutoCommitQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetSetAutoCommitQuery), arg0)
}

// GetSetCatalogQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetSetCatalogQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetCatalogQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetCatalogQuery indicates an expected call of GetSetCatalogQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetSetCatalogQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetCatalogQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetSetCatalogQuery), arg0)
}

// GetSetReadOnlyQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetSetReadOnlyQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetReadOnlyQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetReadOnlyQuery indicates an expected call of GetSetReadOnlyQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetSetReadOnlyQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetReadOnlyQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetSetReadOnlyQuery), arg0)
}

// GetSetSchemaQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetSetSchemaQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetSchemaQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetSchemaQuery indicates an expected call of GetSetSchemaQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetSetSchemaQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetSchemaQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetSetSchemaQuery), arg0)
}

// GetSetTransactionIsolationQuery mocks base method.
func (m *MockAuroraLimitlessDialect) GetSetTransactionIsolationQuery(arg0 driver_infrastructure.TransactionIsolationLevel) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetTransactionIsolationQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetTransactionIsolationQuery indicates an expected call of GetSetTransactionIsolationQuery.
func (mr *MockAuroraLimitlessDialectMockRecorder) GetSetTransactionIsolationQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetTransactionIsolationQuery", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).GetSetTransactionIsolationQuery), arg0)
}

// IsDialect mocks base method.
func (m *MockAuroraLimitlessDialect) IsDialect(arg0 driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialect", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDialect indicates an expected call of IsDialect.
func (mr *MockAuroraLimitlessDialectMockRecorder) IsDialect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialect", reflect.TypeOf((*MockAuroraLimitlessDialect)(nil).IsDialect), arg0)
}

// MockBlueGreenDialect is a mock of BlueGreenDialect interface.
type MockBlueGreenDialect struct {
	ctrl     *gomock.Controller
	recorder *MockBlueGreenDialectMockRecorder
}

// MockBlueGreenDialectMockRecorder is the mock recorder for MockBlueGreenDialect.
type MockBlueGreenDialectMockRecorder struct {
	mock *MockBlueGreenDialect
}

// NewMockBlueGreenDialect creates a new mock instance.
func NewMockBlueGreenDialect(ctrl *gomock.Controller) *MockBlueGreenDialect {
	mock := &MockBlueGreenDialect{ctrl: ctrl}
	mock.recorder = &MockBlueGreenDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlueGreenDialect) EXPECT() *MockBlueGreenDialectMockRecorder {
	return m.recorder
}

// DoesStatementSetAutoCommit mocks base method.
func (m *MockBlueGreenDialect) DoesStatementSetAutoCommit(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetAutoCommit", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetAutoCommit indicates an expected call of DoesStatementSetAutoCommit.
func (mr *MockBlueGreenDialectMockRecorder) DoesStatementSetAutoCommit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetAutoCommit", reflect.TypeOf((*MockBlueGreenDialect)(nil).DoesStatementSetAutoCommit), arg0)
}

// DoesStatementSetCatalog mocks base method.
func (m *MockBlueGreenDialect) DoesStatementSetCatalog(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetCatalog", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetCatalog indicates an expected call of DoesStatementSetCatalog.
func (mr *MockBlueGreenDialectMockRecorder) DoesStatementSetCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetCatalog", reflect.TypeOf((*MockBlueGreenDialect)(nil).DoesStatementSetCatalog), arg0)
}

// DoesStatementSetReadOnly mocks base method.
func (m *MockBlueGreenDialect) DoesStatementSetReadOnly(arg0 string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetReadOnly", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetReadOnly indicates an expected call of DoesStatementSetReadOnly.
func (mr *MockBlueGreenDialectMockRecorder) DoesStatementSetReadOnly(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetReadOnly", reflect.TypeOf((*MockBlueGreenDialect)(nil).DoesStatementSetReadOnly), arg0)
}

// DoesStatementSetSchema mocks base method.
func (m *MockBlueGreenDialect) DoesStatementSetSchema(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetSchema", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetSchema indicates an expected call of DoesStatementSetSchema.
func (mr *MockBlueGreenDialectMockRecorder) DoesStatementSetSchema(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetSchema", reflect.TypeOf((*MockBlueGreenDialect)(nil).DoesStatementSetSchema), arg0)
}

// DoesStatementSetTransactionIsolation mocks base method.
func (m *MockBlueGreenDialect) DoesStatementSetTransactionIsolation(arg0 string) (driver_infrastructure.TransactionIsolationLevel, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesStatementSetTransactionIsolation", arg0)
	ret0, _ := ret[0].(driver_infrastructure.TransactionIsolationLevel)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoesStatementSetTransactionIsolation indicates an expected call of DoesStatementSetTransactionIsolation.
func (mr *MockBlueGreenDialectMockRecorder) DoesStatementSetTransactionIsolation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesStatementSetTransactionIsolation", reflect.TypeOf((*MockBlueGreenDialect)(nil).DoesStatementSetTransactionIsolation), arg0)
}

// GetBlueGreenStatusQuery mocks base method.
func (m *MockBlueGreenDialect) GetBlueGreenStatusQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlueGreenStatusQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBlueGreenStatusQuery indicates an expected call of GetBlueGreenStatusQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetBlueGreenStatusQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlueGreenStatusQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetBlueGreenStatusQuery))
}

// GetDefaultPort mocks base method.
func (m *MockBlueGreenDialect) GetDefaultPort() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPort")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDefaultPort indicates an expected call of GetDefaultPort.
func (mr *MockBlueGreenDialectMockRecorder) GetDefaultPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPort", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetDefaultPort))
}

// GetDialectUpdateCandidates mocks base method.
func (m *MockBlueGreenDialect) GetDialectUpdateCandidates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialectUpdateCandidates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDialectUpdateCandidates indicates an expected call of GetDialectUpdateCandidates.
func (mr *MockBlueGreenDialectMockRecorder) GetDialectUpdateCandidates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialectUpdateCandidates", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetDialectUpdateCandidates))
}

// GetHostAliasQuery mocks base method.
func (m *MockBlueGreenDialect) GetHostAliasQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostAliasQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHostAliasQuery indicates an expected call of GetHostAliasQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetHostAliasQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostAliasQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetHostAliasQuery))
}

// GetHostListProviderSupplier mocks base method.
func (m *MockBlueGreenDialect) GetHostListProviderSupplier() driver_infrastructure.HostListProviderSupplier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostListProviderSupplier")
	ret0, _ := ret[0].(driver_infrastructure.HostListProviderSupplier)
	return ret0
}

// GetHostListProviderSupplier indicates an expected call of GetHostListProviderSupplier.
func (mr *MockBlueGreenDialectMockRecorder) GetHostListProviderSupplier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostListProviderSupplier", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetHostListProviderSupplier))
}

// GetIsReaderQuery mocks base method.
func (m *MockBlueGreenDialect) GetIsReaderQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsReaderQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIsReaderQuery indicates an expected call of GetIsReaderQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetIsReaderQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsReaderQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetIsReaderQuery))
}

// GetRowParser mocks base method.
func (m *MockBlueGreenDialect) GetRowParser() driver_infrastructure.RowParser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowParser")
	ret0, _ := ret[0].(driver_infrastructure.RowParser)
	return ret0
}

// GetRowParser indicates an expected call of GetRowParser.
func (mr *MockBlueGreenDialectMockRecorder) GetRowParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowParser", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetRowParser))
}

// GetServerVersionQuery mocks base method.
func (m *MockBlueGreenDialect) GetServerVersionQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerVersionQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerVersionQuery indicates an expected call of GetServerVersionQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetServerVersionQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerVersionQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetServerVersionQuery))
}

// GetSetAutoCommitQuery mocks base method.
func (m *MockBlueGreenDialect) GetSetAutoCommitQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetAutoCommitQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetAutoCommitQuery indicates an expected call of GetSetAutoCommitQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetSetAutoCommitQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetAutoCommitQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetSetAutoCommitQuery), arg0)
}

// GetSetCatalogQuery mocks base method.
func (m *MockBlueGreenDialect) GetSetCatalogQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetCatalogQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetCatalogQuery indicates an expected call of GetSetCatalogQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetSetCatalogQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetCatalogQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetSetCatalogQuery), arg0)
}

// GetSetReadOnlyQuery mocks base method.
func (m *MockBlueGreenDialect) GetSetReadOnlyQuery(arg0 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetReadOnlyQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetReadOnlyQuery indicates an expected call of GetSetReadOnlyQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetSetReadOnlyQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetReadOnlyQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetSetReadOnlyQuery), arg0)
}

// GetSetSchemaQuery mocks base method.
func (m *MockBlueGreenDialect) GetSetSchemaQuery(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetSchemaQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetSchemaQuery indicates an expected call of GetSetSchemaQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetSetSchemaQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetSchemaQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetSetSchemaQuery), arg0)
}

// GetSetTransactionIsolationQuery mocks base method.
func (m *MockBlueGreenDialect) GetSetTransactionIsolationQuery(arg0 driver_infrastructure.TransactionIsolationLevel) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetTransactionIsolationQuery", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetTransactionIsolationQuery indicates an expected call of GetSetTransactionIsolationQuery.
func (mr *MockBlueGreenDialectMockRecorder) GetSetTransactionIsolationQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetTransactionIsolationQuery", reflect.TypeOf((*MockBlueGreenDialect)(nil).GetSetTransactionIsolationQuery), arg0)
}

// IsBlueGreenStatusAvailable mocks base method.
func (m *MockBlueGreenDialect) IsBlueGreenStatusAvailable(arg0 driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlueGreenStatusAvailable", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBlueGreenStatusAvailable indicates an expected call of IsBlueGreenStatusAvailable.
func (mr *MockBlueGreenDialectMockRecorder) IsBlueGreenStatusAvailable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlueGreenStatusAvailable", reflect.TypeOf((*MockBlueGreenDialect)(nil).IsBlueGreenStatusAvailable), arg0)
}

// IsDialect mocks base method.
func (m *MockBlueGreenDialect) IsDialect(arg0 driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialect", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDialect indicates an expected call of IsDialect.
func (mr *MockBlueGreenDialectMockRecorder) IsDialect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialect", reflect.TypeOf((*MockBlueGreenDialect)(nil).IsDialect), arg0)
}
