/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: awssql/driver_infrastructure/driver_dialect.go

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	driver "database/sql/driver"
	reflect "reflect"

	host_info_util "github.com/aws/aws-advanced-go-wrapper/awssql/host_info_util"
	gomock "github.com/golang/mock/gomock"
)

// MockDriverDialect is a mock of DriverDialect interface.
type MockDriverDialect struct {
	ctrl     *gomock.Controller
	recorder *MockDriverDialectMockRecorder
}

// MockDriverDialectMockRecorder is the mock recorder for MockDriverDialect.
type MockDriverDialectMockRecorder struct {
	mock *MockDriverDialect
}

// NewMockDriverDialect creates a new mock instance.
func NewMockDriverDialect(ctrl *gomock.Controller) *MockDriverDialect {
	mock := &MockDriverDialect{ctrl: ctrl}
	mock.recorder = &MockDriverDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverDialect) EXPECT() *MockDriverDialectMockRecorder {
	return m.recorder
}

// GetAllowedOnConnectionMethodNames mocks base method.
func (m *MockDriverDialect) GetAllowedOnConnectionMethodNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedOnConnectionMethodNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedOnConnectionMethodNames indicates an expected call of GetAllowedOnConnectionMethodNames.
func (mr *MockDriverDialectMockRecorder) GetAllowedOnConnectionMethodNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedOnConnectionMethodNames", reflect.TypeOf((*MockDriverDialect)(nil).GetAllowedOnConnectionMethodNames))
}

// IsClosed mocks base method.
func (m *MockDriverDialect) IsClosed(conn driver.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClosed", conn)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClosed indicates an expected call of IsClosed.
func (mr *MockDriverDialectMockRecorder) IsClosed(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClosed", reflect.TypeOf((*MockDriverDialect)(nil).IsClosed), conn)
}

// IsDialect mocks base method.
func (m *MockDriverDialect) IsDialect(driver driver.Driver) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDialect", driver)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDialect indicates an expected call of IsDialect.
func (mr *MockDriverDialectMockRecorder) IsDialect(driver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDialect", reflect.TypeOf((*MockDriverDialect)(nil).IsDialect), driver)
}

// IsDriverRegistered mocks base method.
func (m *MockDriverDialect) IsDriverRegistered(drivers map[string]driver.Driver) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDriverRegistered", drivers)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDriverRegistered indicates an expected call of IsDriverRegistered.
func (mr *MockDriverDialectMockRecorder) IsDriverRegistered(drivers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDriverRegistered", reflect.TypeOf((*MockDriverDialect)(nil).IsDriverRegistered), drivers)
}

// IsLoginError mocks base method.
func (m *MockDriverDialect) IsLoginError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoginError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoginError indicates an expected call of IsLoginError.
func (mr *MockDriverDialectMockRecorder) IsLoginError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoginError", reflect.TypeOf((*MockDriverDialect)(nil).IsLoginError), err)
}

// IsNetworkError mocks base method.
func (m *MockDriverDialect) IsNetworkError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNetworkError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNetworkError indicates an expected call of IsNetworkError.
func (mr *MockDriverDialectMockRecorder) IsNetworkError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNetworkError", reflect.TypeOf((*MockDriverDialect)(nil).IsNetworkError), err)
}

// PrepareDsn mocks base method.
func (m *MockDriverDialect) PrepareDsn(properties map[string]string, info *host_info_util.HostInfo) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareDsn", properties, info)
	ret0, _ := ret[0].(string)
	return ret0
}

// PrepareDsn indicates an expected call of PrepareDsn.
func (mr *MockDriverDialectMockRecorder) PrepareDsn(properties, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareDsn", reflect.TypeOf((*MockDriverDialect)(nil).PrepareDsn), properties, info)
}

// RegisterDriver mocks base method.
func (m *MockDriverDialect) RegisterDriver() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterDriver")
}

// RegisterDriver indicates an expected call of RegisterDriver.
func (mr *MockDriverDialectMockRecorder) RegisterDriver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDriver", reflect.TypeOf((*MockDriverDialect)(nil).RegisterDriver))
}
