/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure (interfaces: ServicesContainer)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure"
	telemetry "github.com/aws/aws-advanced-go-wrapper/awssql/v2/utils/telemetry"
	gomock "github.com/golang/mock/gomock"
)

// MockServicesContainer is a mock of ServicesContainer interface.
type MockServicesContainer struct {
	ctrl     *gomock.Controller
	recorder *MockServicesContainerMockRecorder
}

// MockServicesContainerMockRecorder is the mock recorder for MockServicesContainer.
type MockServicesContainerMockRecorder struct {
	mock *MockServicesContainer
}

// NewMockServicesContainer creates a new mock instance.
func NewMockServicesContainer(ctrl *gomock.Controller) *MockServicesContainer {
	mock := &MockServicesContainer{ctrl: ctrl}
	mock.recorder = &MockServicesContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicesContainer) EXPECT() *MockServicesContainerMockRecorder {
	return m.recorder
}

// CreateMinimal mocks base method.
func (m *MockServicesContainer) CreateMinimal() driver_infrastructure.ServicesContainer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMinimal")
	ret0, _ := ret[0].(driver_infrastructure.ServicesContainer)
	return ret0
}

// CreateMinimal indicates an expected call of CreateMinimal.
func (mr *MockServicesContainerMockRecorder) CreateMinimal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMinimal", reflect.TypeOf((*MockServicesContainer)(nil).CreateMinimal))
}

// GetConnectionProvider mocks base method.
func (m *MockServicesContainer) GetConnectionProvider() driver_infrastructure.ConnectionProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionProvider")
	ret0, _ := ret[0].(driver_infrastructure.ConnectionProvider)
	return ret0
}

// GetConnectionProvider indicates an expected call of GetConnectionProvider.
func (mr *MockServicesContainerMockRecorder) GetConnectionProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionProvider", reflect.TypeOf((*MockServicesContainer)(nil).GetConnectionProvider))
}

// GetEventPublisher mocks base method.
func (m *MockServicesContainer) GetEventPublisher() driver_infrastructure.EventPublisher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventPublisher")
	ret0, _ := ret[0].(driver_infrastructure.EventPublisher)
	return ret0
}

// GetEventPublisher indicates an expected call of GetEventPublisher.
func (mr *MockServicesContainerMockRecorder) GetEventPublisher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventPublisher", reflect.TypeOf((*MockServicesContainer)(nil).GetEventPublisher))
}

// GetHostListProviderService mocks base method.
func (m *MockServicesContainer) GetHostListProviderService() driver_infrastructure.HostListProviderService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostListProviderService")
	ret0, _ := ret[0].(driver_infrastructure.HostListProviderService)
	return ret0
}

// GetHostListProviderService indicates an expected call of GetHostListProviderService.
func (mr *MockServicesContainerMockRecorder) GetHostListProviderService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostListProviderService", reflect.TypeOf((*MockServicesContainer)(nil).GetHostListProviderService))
}

// GetMonitorService mocks base method.
func (m *MockServicesContainer) GetMonitorService() driver_infrastructure.MonitorService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitorService")
	ret0, _ := ret[0].(driver_infrastructure.MonitorService)
	return ret0
}

// GetMonitorService indicates an expected call of GetMonitorService.
func (mr *MockServicesContainerMockRecorder) GetMonitorService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitorService", reflect.TypeOf((*MockServicesContainer)(nil).GetMonitorService))
}

// GetPluginManager mocks base method.
func (m *MockServicesContainer) GetPluginManager() driver_infrastructure.PluginManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPluginManager")
	ret0, _ := ret[0].(driver_infrastructure.PluginManager)
	return ret0
}

// GetPluginManager indicates an expected call of GetPluginManager.
func (mr *MockServicesContainerMockRecorder) GetPluginManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginManager", reflect.TypeOf((*MockServicesContainer)(nil).GetPluginManager))
}

// GetPluginService mocks base method.
func (m *MockServicesContainer) GetPluginService() driver_infrastructure.PluginService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPluginService")
	ret0, _ := ret[0].(driver_infrastructure.PluginService)
	return ret0
}

// GetPluginService indicates an expected call of GetPluginService.
func (mr *MockServicesContainerMockRecorder) GetPluginService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginService", reflect.TypeOf((*MockServicesContainer)(nil).GetPluginService))
}

// GetStorageService mocks base method.
func (m *MockServicesContainer) GetStorageService() driver_infrastructure.StorageService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageService")
	ret0, _ := ret[0].(driver_infrastructure.StorageService)
	return ret0
}

// GetStorageService indicates an expected call of GetStorageService.
func (mr *MockServicesContainerMockRecorder) GetStorageService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageService", reflect.TypeOf((*MockServicesContainer)(nil).GetStorageService))
}

// GetTelemetryFactory mocks base method.
func (m *MockServicesContainer) GetTelemetryFactory() telemetry.TelemetryFactory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetryFactory")
	ret0, _ := ret[0].(telemetry.TelemetryFactory)
	return ret0
}

// GetTelemetryFactory indicates an expected call of GetTelemetryFactory.
func (mr *MockServicesContainerMockRecorder) GetTelemetryFactory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetryFactory", reflect.TypeOf((*MockServicesContainer)(nil).GetTelemetryFactory))
}
