/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure (interfaces: RowParser)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	driver "database/sql/driver"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRowParser is a mock of RowParser interface.
type MockRowParser struct {
	ctrl     *gomock.Controller
	recorder *MockRowParserMockRecorder
}

// MockRowParserMockRecorder is the mock recorder for MockRowParser.
type MockRowParserMockRecorder struct {
	mock *MockRowParser
}

// NewMockRowParser creates a new mock instance.
func NewMockRowParser(ctrl *gomock.Controller) *MockRowParser {
	mock := &MockRowParser{ctrl: ctrl}
	mock.recorder = &MockRowParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowParser) EXPECT() *MockRowParserMockRecorder {
	return m.recorder
}

// ParseBool mocks base method.
func (m *MockRowParser) ParseBool(arg0 driver.Value) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBool", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseBool indicates an expected call of ParseBool.
func (mr *MockRowParserMockRecorder) ParseBool(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBool", reflect.TypeOf((*MockRowParser)(nil).ParseBool), arg0)
}

// ParseFloat64 mocks base method.
func (m *MockRowParser) ParseFloat64(arg0 driver.Value) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFloat64", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseFloat64 indicates an expected call of ParseFloat64.
func (mr *MockRowParserMockRecorder) ParseFloat64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFloat64", reflect.TypeOf((*MockRowParser)(nil).ParseFloat64), arg0)
}

// ParseInt64 mocks base method.
func (m *MockRowParser) ParseInt64(arg0 driver.Value) (int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInt64", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseInt64 indicates an expected call of ParseInt64.
func (mr *MockRowParserMockRecorder) ParseInt64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInt64", reflect.TypeOf((*MockRowParser)(nil).ParseInt64), arg0)
}

// ParseString mocks base method.
func (m *MockRowParser) ParseString(arg0 driver.Value) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseString indicates an expected call of ParseString.
func (mr *MockRowParserMockRecorder) ParseString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseString", reflect.TypeOf((*MockRowParser)(nil).ParseString), arg0)
}

// ParseTime mocks base method.
func (m *MockRowParser) ParseTime(arg0 driver.Value) (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTime", arg0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ParseTime indicates an expected call of ParseTime.
func (mr *MockRowParserMockRecorder) ParseTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTime", reflect.TypeOf((*MockRowParser)(nil).ParseTime), arg0)
}
