// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure (interfaces: DriverPropertyResolver)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	reflect "reflect"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/v2/driver_infrastructure"
	gomock "github.com/golang/mock/gomock"
)

// MockDriverPropertyResolver is a mock of DriverPropertyResolver interface.
type MockDriverPropertyResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverPropertyResolverMockRecorder
}

// MockDriverPropertyResolverMockRecorder is the mock recorder for MockDriverPropertyResolver.
type MockDriverPropertyResolverMockRecorder struct {
	mock *MockDriverPropertyResolver
}

// NewMockDriverPropertyResolver creates a new mock instance.
func NewMockDriverPropertyResolver(ctrl *gomock.Controller) *MockDriverPropertyResolver {
	mock := &MockDriverPropertyResolver{ctrl: ctrl}
	mock.recorder = &MockDriverPropertyResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverPropertyResolver) EXPECT() *MockDriverPropertyResolverMockRecorder {
	return m.recorder
}

// CreateProps mocks base method.
func (m *MockDriverPropertyResolver) CreateProps(arg0 ...driver_infrastructure.DriverPropertyOption) map[string]string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProps", varargs...)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// CreateProps indicates an expected call of CreateProps.
func (mr *MockDriverPropertyResolverMockRecorder) CreateProps(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProps", reflect.TypeOf((*MockDriverPropertyResolver)(nil).CreateProps), arg0...)
}

// FormatValue mocks base method.
func (m *MockDriverPropertyResolver) FormatValue(arg0 driver_infrastructure.DriverPropertyKey, arg1 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatValue", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatValue indicates an expected call of FormatValue.
func (mr *MockDriverPropertyResolverMockRecorder) FormatValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatValue", reflect.TypeOf((*MockDriverPropertyResolver)(nil).FormatValue), arg0, arg1)
}

// GetPropertyName mocks base method.
func (m *MockDriverPropertyResolver) GetPropertyName(arg0 driver_infrastructure.DriverPropertyKey) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPropertyName", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPropertyName indicates an expected call of GetPropertyName.
func (mr *MockDriverPropertyResolverMockRecorder) GetPropertyName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPropertyName", reflect.TypeOf((*MockDriverPropertyResolver)(nil).GetPropertyName), arg0)
}
