/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure (interfaces: StorageService,RawStorageAccess)

// Package mock_driver_infrastructure is a generated GoMock package.
package mock_driver_infrastructure

import (
	reflect "reflect"
	time "time"

	driver_infrastructure "github.com/aws/aws-advanced-go-wrapper/awssql/driver_infrastructure"
	gomock "github.com/golang/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockStorageService) Clear(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear", arg0)
}

// Clear indicates an expected call of Clear.
func (mr *MockStorageServiceMockRecorder) Clear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockStorageService)(nil).Clear), arg0)
}

// ClearAll mocks base method.
func (m *MockStorageService) ClearAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearAll")
}

// ClearAll indicates an expected call of ClearAll.
func (mr *MockStorageServiceMockRecorder) ClearAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAll", reflect.TypeOf((*MockStorageService)(nil).ClearAll))
}

// Exists mocks base method.
func (m *MockStorageService) Exists(arg0 string, arg1 interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockStorageServiceMockRecorder) Exists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStorageService)(nil).Exists), arg0, arg1)
}

// Register mocks base method.
func (m *MockStorageService) Register(arg0 string, arg1 time.Duration, arg2 bool, arg3 driver_infrastructure.ShouldDisposeFunc, arg4 driver_infrastructure.ItemDisposalFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0, arg1, arg2, arg3, arg4)
}

// Register indicates an expected call of Register.
func (mr *MockStorageServiceMockRecorder) Register(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockStorageService)(nil).Register), arg0, arg1, arg2, arg3, arg4)
}

// Remove mocks base method.
func (m *MockStorageService) Remove(arg0 string, arg1 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", arg0, arg1)
}

// Remove indicates an expected call of Remove.
func (mr *MockStorageServiceMockRecorder) Remove(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockStorageService)(nil).Remove), arg0, arg1)
}

// Size mocks base method.
func (m *MockStorageService) Size(arg0 string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockStorageServiceMockRecorder) Size(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockStorageService)(nil).Size), arg0)
}

// Stop mocks base method.
func (m *MockStorageService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockStorageServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStorageService)(nil).Stop))
}

// MockRawStorageAccess is a mock of RawStorageAccess interface.
type MockRawStorageAccess struct {
	ctrl     *gomock.Controller
	recorder *MockRawStorageAccessMockRecorder
}

// MockRawStorageAccessMockRecorder is the mock recorder for MockRawStorageAccess.
type MockRawStorageAccessMockRecorder struct {
	mock *MockRawStorageAccess
}

// NewMockRawStorageAccess creates a new mock instance.
func NewMockRawStorageAccess(ctrl *gomock.Controller) *MockRawStorageAccess {
	mock := &MockRawStorageAccess{ctrl: ctrl}
	mock.recorder = &MockRawStorageAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawStorageAccess) EXPECT() *MockRawStorageAccessMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRawStorageAccess) Get(arg0 string, arg1 interface{}) (interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRawStorageAccessMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRawStorageAccess)(nil).Get), arg0, arg1)
}

// Set mocks base method.
func (m *MockRawStorageAccess) Set(arg0 string, arg1, arg2 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1, arg2)
}

// Set indicates an expected call of Set.
func (mr *MockRawStorageAccessMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRawStorageAccess)(nil).Set), arg0, arg1, arg2)
}
