name: Benchmark Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Test with Go'
        working-directory: ${{ github.workspace }}/.test
        run: go test ./test -benchmem -bench=Benchmark -run=^$ > BenchmarkResults.txt
      - name: 'Upload Go test results'
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Go-Benchmarks
          path: ${{ github.workspace }}/.test/BenchmarkResults.txt
          retention-days: 5
          