name: Tidy Dependabot PR

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "dependabot/go_modules/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  tidy-dependabot-pr:
    name: Tidy dependabot PR - Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Find and tidy Go modules
        id: run-tidy
        run: |
          # Find all directories containing go.mod files
          modules=$(find . -type f -name 'go.mod' -exec dirname {} \;)
          
          # Run go mod tidy on each module
          for dir in $modules; do
            echo "Running go mod tidy in $dir"
            cd "$dir"
            go mod tidy
            cd - > /dev/null
          done
          
          # Check if there are any changes
          git diff > diff.txt
          if [ -s diff.txt ]; then
            echo "Changes detected after running go mod tidy"
            echo "diff=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected after running go mod tidy"
            echo "diff=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit
        if: ${{ steps.run-tidy.outputs.diff == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'dependabot'
          git config --global user.email 'dependabot@github.com'
          git add .
          git commit -m "chore: automatic commit created after go mod tidy"
          git push

  tidy-dependabot-push:
    name: Tidy dependabot PR - Push
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ steps.pr.outputs.pull_request_number }}
      - name: Find and tidy Go modules
        id: run-tidy
        run: |
          # Find all directories containing go.mod files
          modules=$(find . -type f -name 'go.mod' -exec dirname {} \;)
          
          # Run go mod tidy on each module
          for dir in $modules; do
            echo "Running go mod tidy in $dir"
            cd "$dir"
            go mod tidy
            cd - > /dev/null
          done
          
          # Check if there are any changes
          git diff > diff.txt
          if [ -s diff.txt ]; then
            echo "Changes detected after running go mod tidy"
            echo "diff=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected after running go mod tidy"
            echo "diff=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit
        if: ${{ steps.run-tidy.outputs.diff == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'dependabot'
          git config --global user.email 'dependabot@github.com'
          git add .
          git commit -m "chore: automatic commit created after go mod tidy"
          git push
