name: Tidy Dependabot PR

on:
  pull-request:
    branches:
      - "main"
  push:
    branches:
      - "dependabot/go_modules/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  tidy-dependabot-pr:
    name: Tidy dependabot PR - Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Run go mod tidy
        run: go mod tidy
      - name: Commit
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git add .
          git commit -m "chore: automatic commit created after go mod tidy"
          git push
  tidy-dependabot-push:
    name: Tidy dependabot PR - Push
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ steps.pr.outputs.pull_request_number }}
      - name: Run go mod tidy
        id: run-tidy
        run: |
          go mod tidy
          echo "diff=$(git diff)" >> $GITHUB_OUTPUT
      - name: Commit
        if: ${{ steps.run-tidy.outputs.diff != '' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git add .
          git commit -m "chore: automatic commit created after go mod tidy"
          git push