name: Build, Unit Tests, and Linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
      - name: 'Run golangci-lint - linting'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m
      - name: 'Install dependencies'
        run: go get .
      - name: 'Test with Go'
        run: go test . ./test -json > TestResults.json
      - name: 'Upload Go test results'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: TestResults.json
          retention-days: 5
          